---

- name: install systemd
  package:
    name: systemd

- name: deploy network configuration files
  template:
    src: template.network.j2
    dest: '/etc/systemd/network/{{ item.name }}.network'
    owner: root
    group: root
    mode: 0644
  loop: '{{ systemd_networkd_networks }}'
  loop_control:
    label: '{{ item.name }}'
  register: systemd_networkd_configuration
  tags:
    - configuration
    - systemd-networkd-configuration

- name: restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
  when: systemd_networkd_configuration.changed

- name: enable systemd-networkd service and assure it is started
  systemd:
    name: systemd-networkd
    enabled: yes
    state: started
  tags:
    - service

...
